services:
  lilium-nest-mainnet:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '4093:4000'
    env_file:
      - .env.mainnet

  lilium-nest-testnet:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '4092:4000'
    env_file:
      - .env.testnet

  db:
    image: rapidfort/postgresql:16.0.0
    env_file:
      - .env.mainnet
    volumes:
      - postgres-data:/bitnami/postgresql
    restart: always

volumes:
  postgres-data:
